### PR TITLE
Use python3 everywhere

### PR DESCRIPTION
**Pull request by hroncok**
cc @frantisekz

Let's see what breaks.

### CODE REVIEW

**Comment by hroncok** [comment]
So apparently (as expected) everything fails totally.

**Comment by hroncok** [comment]
The downloader doesn't have the libtaskotron module.

    ModuleNotFoundError: No module named 'libtaskotron'

**Comment by hroncok** [comment]
There are RPMs missing to be able to run this:

```console
$ dnf repoquery --repo=rawhide -f /usr/lib/python2.7/site-packages/libtaskotron/__init__.py
libtaskotron-core-0:0.9.0-1.fc30.noarch
$ dnf repoquery --repo=rawhide -f /usr/lib/python3.7/site-packages/libtaskotron/__init__.py
(nothing)
```

**Comment by frantisekz** [comment]
Yes, I am planning to build Py3 Taskotron in Rawhide soon™ . For now, the packages are available here: https://copr.fedorainfracloud.org/coprs/kparal/taskotron-dev/builds/

**Comment by hroncok** [comment]
So there was a bug with bytes encoded requires leaking `b''` into the log.
I've decided to get it solved properly by not dealing with bytes encoded requires at all.
Should work now. I guess.

**Comment by frantisekz** [comment]
Ok, it seems it's working fine on our dev instance: https://taskotron-dev.fedoraproject.org

**Comment by hroncok** [comment]
rawhide test failing. But the fial is in mock init, so something is weird, will rerun it.

**Comment by hroncok** [comment]
This seems to work.

Can this go into develop?

**Comment by frantisekz** [comment]
> This seems to work.
> 
> Can this go into develop?

Yes, but please, keep the "python3" branch in sync with it, if you want to add and run the new commits on taskotron-dev.

**Comment by frantisekz** [comment]
Right about now :)
https://koji.fedoraproject.org/koji/buildinfo?buildID=1161786

If everything goes without any issues, it should be deployed to production sometimes next week.

**Comment by hroncok** [comment]
Current state: Dropped the copr repo, the tests will fail, as the update is still pending to stable, but rawhide might work. Tomorrow, I'll rerun the tests.

I will merge this to devel as soon as the tests succeeds. (Let me know when I can remove the python3 branch).

After a day or two, I merge to master as well (let me know if I should not).

**Comment by frantisekz** [comment]
Python 3 Taskotron is in stable repos now and it's been deployed to the production instance.

**Pull request merged**
